# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-21 20:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='id')),
                ('title', models.CharField(db_column='title', error_messages={'invalid': 'Enter a valid title.'}, help_text='Required. 180 character or fewer.', max_length=180, verbose_name='title')),
                ('text', models.TextField(db_column='text', error_messages={'invalid': 'Your question not valid. Check text and try again.'}, help_text='Required. 30000 character or fewer. Ask a question.', max_length=30000, verbose_name='text')),
                ('date_created', models.DateTimeField(auto_now_add=True, db_column='date_created', verbose_name='date created')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user id')),
            ],
            options={
                'db_table': 'questions',
                'verbose_name': 'Questions',
            },
        ),
    ]
