# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-18 18:55
from __future__ import unicode_literals

import apps.accounts.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, db_column='avatar', error_messages={'invalid': 'Please choice a valid image format.'}, upload_to=apps.accounts.models.upload_avatar_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mpeg', 'ras', 'pdf', 'tga', 'jpf', 'jpe', 'xpm', 'jfif', 'emf', 'mpg', 'ftc', 'cur', 'pcx', 'j2c', 'rgba', 'pgm', 'ico', 'jpx', 'pcd', 'pbm', 'webp', 'wmf', 'ftu', 'png', 'tiff', 'hdf', 'palm', 'fits', 'im', 'rgb', 'flc', 'psd', 'dds', 'ppm', 'jp2', 'h5', 'jpeg', 'jpc', 'eps', 'gbr', 'iim', 'ps', 'pxr', 'fit', 'gif', 'fli', 'j2k', 'icns', 'bw', 'bufr', 'sgi', 'dcx', 'jpg', 'bmp', 'msp', 'tif', 'xbm', 'mpo', 'grib'])], verbose_name='avatar'),
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
