# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-18 20:47
from __future__ import unicode_literals

import apps.accounts.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20180118_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, db_column='avatar', error_messages={'invalid': 'Please choice a valid image format.'}, upload_to=apps.accounts.models.upload_avatar_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['ps', 'h5', 'gbr', 'eps', 'msp', 'rgb', 'bw', 'psd', 'palm', 'ppm', 'j2c', 'iim', 'mpg', 'tiff', 'cur', 'webp', 'jpe', 'jpx', 'gif', 'jp2', 'tif', 'pcd', 'jpg', 'pbm', 'mpo', 'ico', 'ftu', 'pxr', 'jpeg', 'hdf', 'wmf', 'xpm', 'emf', 'dcx', 'pdf', 'jpc', 'tga', 'icns', 'dds', 'grib', 'pgm', 'png', 'xbm', 'pcx', 'rgba', 'jpf', 'jfif', 'bmp', 'j2k', 'bufr', 'fit', 'ras', 'im', 'fits', 'ftc', 'fli', 'flc', 'mpeg', 'sgi'])], verbose_name='avatar'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
