# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-22 16:17
from __future__ import unicode_literals

import apps.accounts.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20180122_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, db_column='avatar', error_messages={'invalid': 'Please choice a valid image format.'}, upload_to=apps.accounts.models.upload_avatar_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['eps', 'gbr', 'tga', 'fits', 'jpeg', 'sgi', 'fli', 'xpm', 'webp', 'ppm', 'iim', 'h5', 'jpf', 'mpeg', 'grib', 'psd', 'pbm', 'icns', 'ps', 'fit', 'palm', 'msp', 'tiff', 'bmp', 'gif', 'xbm', 'rgb', 'j2c', 'cur', 'jpx', 'tif', 'jpc', 'j2k', 'bw', 'pcd', 'hdf', 'ras', 'im', 'ftu', 'rgba', 'flc', 'ftc', 'jpe', 'dcx', 'pdf', 'jfif', 'png', 'mpg', 'wmf', 'jp2', 'pxr', 'emf', 'ico', 'pgm', 'mpo', 'bufr', 'jpg', 'dds', 'pcx'])], verbose_name='avatar'),
        ),
    ]
