# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-22 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20180122_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(db_column='text', error_messages={'invalid': 'Your question not valid. Check text and try again.'}, help_text='Required. 30000 characters limit. Ask a question.', max_length=30000, verbose_name='text'),
        ),
    ]
