# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-22 16:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0003_auto_20180122_1916'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='id')),
                ('text', models.TextField(db_column='text', error_messages={'invalid': 'Your answer not valid. Check text and try again.'}, help_text='Required. 30000 character limit. Answer the question.', max_length=30000, verbose_name='text')),
                ('date_created', models.DateTimeField(auto_now_add=True, db_column='date_column', verbose_name='date_created')),
                ('question_id', models.OneToOneField(db_column='question_id', on_delete=django.db.models.deletion.CASCADE, to='questions.Question', verbose_name='question id')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user id')),
            ],
            options={
                'verbose_name': 'Answers',
                'db_table': 'answers',
            },
        ),
    ]
