# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-21 20:55
from __future__ import unicode_literals

import apps.accounts.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, db_column='avatar', error_messages={'invalid': 'Please choice a valid image format.'}, upload_to=apps.accounts.models.upload_avatar_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['psd', 'mpg', 'pcd', 'gbr', 'jpe', 'sgi', 'jp2', 'im', 'jfif', 'j2c', 'jpx', 'mpeg', 'png', 'j2k', 'iim', 'pcx', 'ico', 'pgm', 'tga', 'gif', 'xpm', 'rgba', 'ftu', 'cur', 'hdf', 'ftc', 'palm', 'pxr', 'bmp', 'dcx', 'rgb', 'jpeg', 'eps', 'icns', 'webp', 'jpf', 'grib', 'tif', 'dds', 'jpg', 'pdf', 'xbm', 'fits', 'bufr', 'flc', 'ras', 'tiff', 'h5', 'ppm', 'pbm', 'fli', 'emf', 'ps', 'wmf', 'msp', 'mpo', 'jpc', 'bw', 'fit'])], verbose_name='avatar'),
        ),
    ]
