# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-21 21:15
from __future__ import unicode_literals

import apps.accounts.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180121_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, db_column='avatar', error_messages={'invalid': 'Please choice a valid image format.'}, upload_to=apps.accounts.models.upload_avatar_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['ico', 'jp2', 'ppm', 'dds', 'rgba', 'jpg', 'wmf', 'pbm', 'hdf', 'psd', 'rgb', 'pcd', 'eps', 'ftc', 'gif', 'msp', 'pxr', 'dcx', 'bw', 'icns', 'mpo', 'pgm', 'png', 'iim', 'tiff', 'ras', 'mpg', 'h5', 'jpc', 'mpeg', 'gbr', 'im', 'webp', 'jpx', 'xpm', 'cur', 'bufr', 'fits', 'pcx', 'emf', 'grib', 'j2k', 'tga', 'fit', 'tif', 'ftu', 'xbm', 'pdf', 'palm', 'flc', 'j2c', 'fli', 'ps', 'jpe', 'jfif', 'jpf', 'bmp', 'sgi', 'jpeg'])], verbose_name='avatar'),
        ),
    ]
