# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-22 16:16
from __future__ import unicode_literals

import apps.accounts.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20180122_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, db_column='avatar', error_messages={'invalid': 'Please choice a valid image format.'}, upload_to=apps.accounts.models.upload_avatar_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['bw', 'mpg', 'ftc', 'psd', 'jpc', 'webp', 'gbr', 'hdf', 'jfif', 'ftu', 'dds', 'sgi', 'xbm', 'pbm', 'j2c', 'j2k', 'iim', 'gif', 'fits', 'pdf', 'wmf', 'rgba', 'ps', 'msp', 'flc', 'palm', 'mpeg', 'jpf', 'jp2', 'bufr', 'pxr', 'jpx', 'jpeg', 'eps', 'mpo', 'tga', 'fli', 'fit', 'ppm', 'jpe', 'pcx', 'bmp', 'emf', 'jpg', 'cur', 'tif', 'grib', 'rgb', 'pcd', 'h5', 'icns', 'tiff', 'xpm', 'dcx', 'png', 'im', 'pgm', 'ico', 'ras'])], verbose_name='avatar'),
        ),
    ]
