# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-22 17:52
from __future__ import unicode_literals

import apps.accounts.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20180122_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, db_column='avatar', error_messages={'invalid': 'Please choice a valid image format.'}, upload_to=apps.accounts.models.upload_avatar_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['tga', 'xpm', 'tif', 'ico', 'ppm', 'palm', 'tiff', 'jpe', 'ras', 'eps', 'pbm', 'jpg', 'mpo', 'psd', 'h5', 'mpeg', 'dcx', 'gbr', 'bmp', 'bw', 'png', 'fits', 'ps', 'mpg', 'flc', 'jpc', 'msp', 'pgm', 'emf', 'wmf', 'fit', 'sgi', 'pxr', 'grib', 'bufr', 'j2c', 'icns', 'fli', 'gif', 'jpf', 'rgba', 'webp', 'cur', 'xbm', 'ftu', 'jpeg', 'pdf', 'rgb', 'jpx', 'im', 'dds', 'iim', 'jp2', 'pcd', 'jfif', 'pcx', 'hdf', 'ftc', 'j2k'])], verbose_name='avatar'),
        ),
    ]
