# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-23 15:02
from __future__ import unicode_literals

import apps.accounts.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20180122_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, db_column='avatar', error_messages={'invalid': 'Please choice a valid image format.'}, upload_to=apps.accounts.models.upload_avatar_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mpg', 'fits', 'tif', 'fli', 'pgm', 'rgba', 'ftu', 'cur', 'icns', 'fit', 'bufr', 'im', 'iim', 'jpe', 'jpf', 'mpeg', 'dcx', 'j2k', 'jpx', 'dds', 'rgb', 'psd', 'tga', 'ppm', 'xbm', 'ps', 'jp2', 'grib', 'jpg', 'mpo', 'jpc', 'msp', 'flc', 'ras', 'j2c', 'png', 'emf', 'ico', 'bmp', 'h5', 'bw', 'pcd', 'gif', 'sgi', 'gbr', 'xpm', 'pxr', 'ftc', 'pbm', 'tiff', 'webp', 'jpeg', 'palm', 'pcx', 'hdf', 'eps', 'pdf', 'jfif', 'wmf'])], verbose_name='avatar'),
        ),
    ]
